# This file is part of «Birchbark Literacy from Medieval Rus» database.
#
# Copyright (c) Department of Linguistic and Literary Studies of the University of Padova
#
# «Birchbark Literacy from Medieval Rus» database is free software:
# you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, version 3.
#
# «Birchbark Literacy from Medieval Rus» database is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code. If you have not received
# a copy of the GNU General Public License along with
# «Birchbark Literacy from Medieval Rus» database,
# see <http://www.gnu.org/licenses/>.

sonata_media:
  class:
    media: App\Entity\MediaBundle\Media
    gallery: App\Entity\MediaBundle\Gallery
    gallery_has_media: App\Entity\MediaBundle\GalleryHasMedia
  db_driver: doctrine_orm
  default_context: default
  contexts:
    default:
      providers:
        - sonata.media.provider.dailymotion
        - sonata.media.provider.youtube
        - sonata.media.provider.image
        - sonata.media.provider.file
        - sonata.media.provider.vimeo
      formats:
        small: { width: 100 , quality: 70}
        big:   { width: 500 , quality: 70}
    bb__dnd_section:
      providers:
        - sonata.media.provider.file
  cdn:
    server:
      path: /uploads/media
  filesystem:
    local:
      directory: "%kernel.project_dir%/public/uploads/media"
      create: false
  providers:
    image:
      allowed_extensions: ['jpg', 'png', 'gif', 'jpeg']
      allowed_mime_types: ['image/pjpeg','image/jpeg','image/png','image/x-png', 'image/gif']

doctrine:
  orm:
    mappings:
      SonataMediaBundle: ~
